language: node_js
node_js:
  - "node"
branches:
  only:
    - master
git:
  depth: 1
before_install:
  - npm i -g npm@6.12.0
cache: npm
script:
  - export ELASTIC_BEANSTALK_LABEL=$TRAVIS_COMMIT
  - export ELASTIC_BEANSTALK_DESCRIPTION=$TRAVIS_COMMIT_MESSAGE
deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "ap-southeast-1"
    app: "isomer-chatbot"
    env: "isomer-chatbot-test"
    bucket_name: "isomer-chatbot-$TRAVIS_BRANCH"
    wait_until_deployed: true
    on:
      branch: master